### PR TITLE
Fixes to the auto complete problem

### LINKED ISSUE #47: Avoid always having auto complete
Currently, all arguments are registered with auto completions, or with choices. This is not always a good idea because sometimes there's a guarantee that there will be no suggestions returned (like in case of string parser)

I think the suggestions system may need some changes to make this work, I think it's very important because on low end phones discord trying to get auto completions cause delay/lag.

### PR DESCRIPTION
**Pull request by BlueTree242**
This pull request solves auto completion issues. Here are the exact changes:

1. Added a check whether the suggestion provider of an argument is the same one as `SuggestionProvider#noSuggestions()`.
2. Before dealing with the `SuggestionProvider` during registration it would first run the suggestion registration mapper, which will allow you to map providers to discord choices or `SuggestionProvider#noSuggestions()` (disable auto complete) by setting it on the command factory.

The suggestion registration mapper is very useful when mapping providers that return constant values, or provide suggestions that would be barely helpful and you would like to disable it completely.

The suggestion registration mapper might not be the best idea, If you aren't fine with it or have better ways to solve the same problem, Let me know!

resolves #47

### CODE REVIEW

File: cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/DiscordCommandFactory.java [hunk 1]
```diff
@@ -37,4 +39,21 @@ public interface DiscordCommandFactory<C> {
...
     @NonNull DiscordCommand<C> create(@NonNull CommandNode<C> node);
+
+    /**
+     * This allows you to change the way some {@link SuggestionProvider}s are handled during registration of the command. If
+     * you would like to use choices you can return {@link DiscordChoices}, or you could return
+     * {@link SuggestionProvider#noSuggestions()} to disable auto-complete for the argument (option).
+     * @param suggestionRegistrationMapper The function to map suggestion providers to other suggestion provider during
+     *                                     registration of the command to discord.
+     */
+    void setSuggestionRegistrationMapper(@NonNull Function<SuggestionProvider<C>,
```
Comment (Citymonstret) [inline cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/DiscordCommandFactory.java:50]:
```suggestion
    void suggestionRegistrationMapper(@NonNull Function<SuggestionProvider<C>,
```

File: cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/DiscordCommandFactory.java [hunk 2]
```diff
@@ -37,4 +39,21 @@ public interface DiscordCommandFactory<C> {
...
+                                         SuggestionProvider<C>> suggestionRegistrationMapper);
+
+    /**
+     * A getter for the current set suggestion registration mapper.
+     * @see DiscordCommandFactory#setSuggestionRegistrationMapper
+     * @return The current set suggestion registration mapper.
+     */
+    @NonNull Function<SuggestionProvider<C>, SuggestionProvider<C>> getSuggestionRegistrationMapper();
```
Comment (Citymonstret) [inline cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/DiscordCommandFactory.java:58]:
```suggestion
    @NonNull Function<SuggestionProvider<C>, SuggestionProvider<C>> suggestionRegistrationMapper();
```

**Review by Citymonstret — CHANGES_REQUESTED** [review]

File: cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/StandardDiscordCommandFactory.java [hunk 3]
```diff
@@ -147,6 +150,16 @@ public <T extends Number, P extends ArgumentParser<C, T>> void registerRangeMapp
                 .build();
     }
 
+    @Override
+    public void setSuggestionRegistrationMapper(final @NonNull Function<SuggestionProvider<C>, SuggestionProvider<C>> suggestionRegistrationMapper) {
+        this.suggestionRegistrationMapper = Objects.requireNonNull(suggestionRegistrationMapper);
+    }
+
+    @Override
+    public @NonNull Function<SuggestionProvider<C>, SuggestionProvider<C>> getSuggestionRegistrationMapper() {
```
Comment (Citymonstret) [inline cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/StandardDiscordCommandFactory.java:159]:
```suggestion
    public @NonNull Function<SuggestionProvider<C>, SuggestionProvider<C>> suggestionRegistrationMapper() {
```

File: cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/StandardDiscordCommandFactory.java [hunk 4]
```diff
@@ -147,6 +150,16 @@ public <T extends Number, P extends ArgumentParser<C, T>> void registerRangeMapp
                 .build();
     }
 
+    @Override
+    public void setSuggestionRegistrationMapper(final @NonNull Function<SuggestionProvider<C>, SuggestionProvider<C>> suggestionRegistrationMapper) {
```
Comment (Citymonstret) [inline cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/StandardDiscordCommandFactory.java:154]:
```suggestion
    public void suggestionRegistrationMapper(final @NonNull Function<SuggestionProvider<C>, SuggestionProvider<C>> suggestionRegistrationMapper) {
```

File: cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/StandardDiscordCommandFactory.java [hunk 5]
```diff
@@ -201,13 +214,14 @@ public <T extends Number, P extends ArgumentParser<C, T>> void registerRangeMapp
 
         return components.stream()
                 .map(innerComponent -> {
+                    SuggestionProvider<C> suggestionProvider = suggestionRegistrationMapper.apply(innerComponent.suggestionProvider());
```
Comment (Citymonstret) [inline cloud-discord-common/src/main/java/org/incendo/cloud/discord/slash/StandardDiscordCommandFactory.java:217]:
```suggestion
                    SuggestionProvider<C> suggestionProvider = this.suggestionRegistrationMapper.apply(innerComponent.suggestionProvider());
```

**Review by Citymonstret — CHANGES_REQUESTED** [review]

**Review by Citymonstret — APPROVED** [review]
